### ISSUE TITLE
Getting runtime error when I execute shellout agent

### ISSUE THREAD

**Issue by kk21986** [slaney/mcollective-shellout-agent#1]
---

 mco shellout --help
/usr/lib/ruby/site_ruby/1.8/mcollective/pluginmanager.rb:98:in `create_instance': Could not create instance of plugin MCollective::Application::Shellout: (eval):1:in`create_instance': uninitialized constant MCollective::Application::Shellout (RuntimeError)
        from /usr/lib/ruby/site_ruby/1.8/mcollective/pluginmanager.rb:81:in `[]'
        from /usr/lib/ruby/site_ruby/1.8/mcollective/applications.rb:23:in`run'
##         from /usr/bin/mco:24

Please help me to fix this issue.

**Comment by powellnathanj** [comment]
Sorry, for some reason I am not getting emails from Github.  I will take a look this evening.

**Comment by powellnathanj** [comment]
Can you tell me what version of Mcollective you're using?  Also the OS.
